#
# Travis CI configuration file for ZIPC.
#

language: c

jobs:
  include:
    # Linux-specific build stuff
    - os: linux
      dist: focal
      virt: vm
      env:
        - ASAN_OPTIONS=leak_check_at_exit=false
      script: make sanitizer && make test && make cppcheck
      addons:
        apt:
          packages: [cppcheck]

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode12.2
      script: make sanitizer && make test && make clang

notifications:
  email:
    recipients:
      - msweet@msweet.org
